# Generated by Django 2.2.6 on 2019-10-30 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slimeline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='SLIMELINE NAME UNKNOWN', max_length=128)),
                ('owner', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, related_name='slimeline_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='TITLE UNKNOWN', max_length=128)),
                ('content', models.TextField(default='')),
                ('is_private', models.BooleanField(default=False)),
                ('good_slimes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, related_name='event_author', to=settings.AUTH_USER_MODEL)),
                ('slimeline', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course_posts', to='core.Slimeline')),
            ],
        ),
    ]
