# Generated by Django 2.2.6 on 2019-10-31 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slimeline',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.Slimeline'),
        ),
    ]
